version: "3.4"

volumes:
  prometheus-data:

networks:
  net:
    name: appmetrics
    external: false

services: 
  appmetricsapi:
    image: appmetricsapi
    container_name: appmetricsapi
    build:
      context: src/Services/API/
      dockerfile: Dockerfile
    ports:
      - 9000:80      
    environment:      
      - ASPNETCORE_URLS=http://+:80
    networks:
      - net
      
  appmetricsapipost:
    image: appmetricsapipost
    container_name: appmetricsapipost
    build:
      context: src/Services/APIPost/
      dockerfile: Dockerfile
    ports:
      - 9001:90      
    environment:      
      - ASPNETCORE_URLS=http://+:90
    networks:
      - net
      
  prometheus:
    image: quay.io/prometheus/prometheus:latest
    ports:
      - 9090:9090
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml
    depends_on:
      - appmetricsapi
    networks:
      - net